### ISSUE TITLE
nginx fails to load if ipv6 disabled on host system

### ISSUE THREAD

**Issue by bstock84** [solipsist01/MangosZero#1]
If ipv6 is disabled on the host system, the following line causes nginx to fail to load thus not being able to access the web interface.

File: /etc/nginx/sites-enabled/default

```listen [::]:80 default_server;```

Not sure if there's a way to enable it only if ipv6 is enabled or not. I have to install vim and edit that line if I rebuild the container.

**Comment by solipsist01** [comment]
I could make a check and let it autochange the config based on the presence of ipv6.

Can you run the following command in your container?
```
test -f /proc/net/if_inet6 && echo "IPv6 supported" || echo "IPv6 not supported"
```
Does it say IPv6 not supported?
When i run the command in my environment, it says that IPv6 is supported.
if this works, i'll change the startup script to remove that line if there's no ipv6 support.

**Comment by bstock84** [comment]
That seems to work, it came back saying 'IPv6 not supported' :)

**Comment by solipsist01** [comment]
I have changed the prepmangos procedure, to remove the line when IPv6 is not supported.
Can you test if this works like expected? :)

**Comment by bstock84** [comment]
Tested with latest image and indeed it started working properly, thanks!
