### ISSUE TITLE
InstallWowfiles.sh not taking advantage of multi-core systems for movemap-generator

### ISSUE THREAD

**Issue by bstock84** [solipsist01/MangosZero#3]
The movemap-generator process is by far the longest running item to get everything working, and it can be made considerably faster.

Your script only runs the executable on a single thread. It can be greatly sped up with the following:

./movemap-generator --threads 6

Of course how many to use depends on how many cores are allocated to the host system. Possible solutions could be having the script prompt to ask how many threads to allocate with a default of 1, or perhaps use the output from 'nproc --all' and allocate that many -1 (to leave room for overhead of this container or other containers on the same host system), or a combination of the two (prompt but default to nproc -1 or something similar).

For context I'm running a linux VM which is my docker host and it's given 8 threads (from E5-2650 @2GHz). It's running about 8 other docker containers that are mostly idle. I gave the movemap-generator 7 threads to work with and saw no side-effects to my VM host or the other docker containers.

**Comment by solipsist01** [comment]
I never knew this process could be multithreaded, so that's nice :)
I have made changes to the script to be multithreaded.

It will always take the maximum amount of cores minus 1
except if there's only one core, then it will take 1 core.

```
cores=$(nproc --ignore=1)
if [ "$cores" == "0" ]; then
   cores="1"
fi

./movemap-generator --threads $cores

```

Tested, and works :)

**Comment by solipsist01** [comment]
After some testing with nproc, nproc never will show 0 cores
if i do nproc --ignore=999999. it will still show 1 core. 
I'm removing the checking routine

**Comment by bstock84** [comment]
Everything looks great, tested with the latest image and it's using 7 cores as expected.
