### ISSUE TITLE
playerbot

### ISSUE THREAD

**Issue by serxoz** [solipsist01/MangosZero#6]
Hi!
Hope you could help, I don't get what I'm missing...
I launch the docker container like this:
```sh
docker run \
        --name=vanilla \
        -d \
        -p 81:80 \
        -p 8085:8085 \
        -p 3724:3724 \
        -p 3443:3443 \
        -e PUID=0 -e PGID=0 \
        -e WAN_IP_ADDRESS=x.x.x.x \
        -e DOCKER_HOST_IP=x.x.x.x \
        -e MYSQL_ROOT_PASSWORD=mangos \
        -e TZ=Europe/Amsterdam \
        -v /srv/wowserver/config:/config \
        -v /srv/wowserver/aiplayerbot.conf:/etc/aiplayerbot.conf \
        -v /srv/wowserver/ahbot.conf:/etc/ahbot.conf \
        --restart always \
        solipsist01/mangoszero
```
And I've added to the bottom of  mangosd.conf the following lines:
```
PlayerbotAI.DisableBots = 0
PlayerbotAI.DebugWhisper = 0
PlayerbotAI.FollowDistanceMin = 0.5
PlayerbotAI.FollowDistanceMax = 1.0
PlayerbotAI.MaxNumBots = 9
PlayerbotAI.RestrictBotLevel = 60
PlayerbotAI.BotguyQuests = ""
PlayerbotAI.BotguyCost = 0
PlayerbotAI.Collect.Combat = 1
PlayerbotAI.Collect.Quest = 1
PlayerbotAI.Collect.Profession = 1
PlayerbotAI.Collect.Loot = 1
PlayerbotAI.Collect.Skin = 1
PlayerbotAI.Collect.Objects = 1
PlayerbotAI.Collect.DistanceMax = 50
PlayerbotAI.Collect.Distance = 25
PlayerbotAI.SellGarbage = 0
PlayerbotAI.SellAll.LevelDiff = 10
```   
I get the world populated with random bots that I can invite to the party but when I send a ".bot" command I get nothing in return, nothing nor an error...
What I am missing?

Thank you in advance! :D

**Comment by solipsist01** [comment]
I actually don't use the playerbots.
i've done some scouring on the internet, and it appears they've changed the playerbots.
this is the current documentation
http://ike3.github.io/mangosbot-docs/doc/playerbot/QuickStart.html

i've read that .bot is used to add a character of your own as a bot
so you have to create an extra character, and with .bot you can add this character as a bot.

if this doesn't help, can you paste your complete configuration?
when i have some free time, i will figure it out :)

**Comment by serxoz** [comment]
Yes, I've read the ike3 documentation. I think I've tried everything but couldn't make it work ...
Our idea is to play on Blackrock Depths, or similar, some friends and try to add missing players with bots. I think I'll try to add randombots through the console...
Btw, if you get bored and want to give it a try here are my config files:
[config.tar.gz](https://github.com/solipsist01/MangosZero/files/5751793/config.tar.gz)

Thank you so much for your time! :D

**Comment by solipsist01** [comment]
i've tested your config, and at first i had the same problem as you described.

It was solved when i changed my account in the realmd database from GMLEVEL 0 to GMLEVEL 3
Then it works flawlessly :)

**Comment by serxoz** [comment]
Oh sh.t! Never thought on that...
Thank you so much :D

**Comment by solipsist01** [comment]
Np and enjoy :)
