### ISSUE TITLE
cant login server

### ISSUE THREAD

**Issue by taiwan-king** [solipsist01/MangosZero#7]
[world-server.log](https://github.com/solipsist01/MangosZero/files/8359489/world-server.log)

https://user-images.githubusercontent.com/24381898/160323511-914a73f9-6a1b-4036-8d7e-c134de0d7884.mp4

I used synology docker to build this server.
The process is fully complied with the operating manual.

Even if I change Host_IP to 172.18.1.1 and use updatip.sh and then restart docker, I still cannot log in to the server. 

![01](https://user-images.githubusercontent.com/24381898/160325280-9fecde21-c772-46f1-906d-cd95a04386b8.jpg)
![02](https://user-images.githubusercontent.com/24381898/160325286-caa104cb-7b14-4827-8ec6-9309d3f4c73a.jpg)

client download from https://zremax.com/blog/vanilla-wow-client-download-1-12-1
A 1.12.1 Client provided by Elysium

**Comment by solipsist01** [comment]
Your portmaps are wrong.

3306 should be mapped to 3306 and so on. Not 49473

**Comment by taiwan-king** [comment]
Dear solipsist01:
[world-server.log](https://github.com/solipsist01/MangosZero/files/8368587/world-server.log)
same issue
![1648533364341](https://user-images.githubusercontent.com/24381898/160543180-a6bd78d3-1736-42a9-a3fc-824c3927ff74.jpg)

My lan ip can directly lead to docker ip
so the previous port is the port of my NAS port corresponding to docker
My connection is directly through docker ip 172.18.1.1
nas ip 192.168.10.253

Basically I don't use the WAN IP setting very much, because I will directly import the external connection to 172.18.1.1
[world-server.log](https://github.com/solipsist01/MangosZero/files/8368587/world-server.log)



Below is my connection diagram

My PC ->172.18.1.1:3306

not
MY PC -> 192.168.10.253:3306 map to 172.18.1.1:3306


telnet 172.18.1.1:3306  error
telnet 172.18.1.1:80 is ok
all other port is ok
![01](https://user-images.githubusercontent.com/24381898/160553476-6d080a63-5f98-41cf-a306-64028846bb89.jpg)
![1648537882104](https://user-images.githubusercontent.com/24381898/160554250-5bbd3dea-0485-467e-b8bc-cd8d315cb277.jpg)

**Comment by solipsist01** [comment]
the wan ip and/or host ip is required, because that ip is hardcoded in the database.
127.0.0.1 isn't gonna work.

can you please change the WAN_IP_ADDRESS and DOCKER_HOST_IP variable to your docker host ip addres (synology nas)
and then run updatewanip.sh, and then restart the container.

**Comment by taiwan-king** [comment]
Dear solipsist01:
[world-server.log](https://github.com/solipsist01/MangosZero/files/8376226/world-server.log)

![擷取](https://user-images.githubusercontent.com/24381898/160736045-50ddfb4b-1b5c-418e-946a-d09ee0a48e5a.PNG)

or

![擷取](https://user-images.githubusercontent.com/24381898/160737790-0ad07f01-0cf4-43f3-8341-a73f2d3aa01a.PNG)

result=>

![1648605694620](https://user-images.githubusercontent.com/24381898/160736061-5c426dc3-4f06-45be-b4dd-6b984ba8a96f.jpg)

In fact, I tried these steps.
So I open case.

if i change this
![擷取(1)](https://user-images.githubusercontent.com/24381898/160739602-67647c32-0bfb-4348-904f-9211b8798429.PNG)

result ->
![擷取1](https://user-images.githubusercontent.com/24381898/160739633-0d0cb085-ca09-47f3-855d-874119aa8945.PNG)

my account is gmlevel 3
![01](https://user-images.githubusercontent.com/24381898/161204071-0d08c097-0fad-4c49-be59-45a68d1f4d23.jpg)
[world-remote-access.log](https://github.com/solipsist01/MangosZero/files/8395035/world-remote-access.log)


I found another problem.
![1648667705558](https://user-images.githubusercontent.com/24381898/160913432-2cd2d503-321c-4867-bd3c-c15e17317adb.jpg)
![01](https://user-images.githubusercontent.com/24381898/160915658-2118bbb1-5e35-4ca3-b282-fbde60540fe6.jpg)

[world-remote-access.log](https://github.com/solipsist01/MangosZero/files/8383470/world-remote-access.log)


Sorry, because I have not enough ability, there is no way to set up a server in Synology NAS.
Because these teaching documents are used for Linux cli users.
Is there a teaching document with Synology docker?

I use this person's docker container to run normally.
https://www.programminghunter.com/article/1772149520/

**Comment by raofei** [comment]
> taiwan-king

hi,I have the same situation. Just set the synology ip as the address field in realmlist table in docker. delete the wdb and wtf folder in wow game directory. the first time login will be ok and you can create role and play game,but when you logout .you could not login again.the server show you that the server is disconnect... but.. but ..but.. when you delete the wdb and wtf folder again ,you can login and play game again... my god~~~wtf!!!

**Comment by raofei** [comment]
when you use a origin [MangosZero] database in synology not in docker. Just use the docker as a mangos and realmd server. config the conf files  to connect  synology's mariadb. All is ok~~ I don't know why..
