### ISSUE TITLE
Why I cant start  the image in windows wsl. always tell me that I must  go to login.

### ISSUE THREAD

**Issue by viweei** [solipsist01/MangosZero#9]
![image](https://github.com/solipsist01/MangosZero/assets/1762036/7885ced1-3df9-4861-b852-580b61b98564)

**Comment by solipsist01** [comment]
Try your world of warcraft folder without spaces, or use quotes.

Its trying to download of/mangoszero

**Comment by viweei** [comment]
@solipsist01  nice~ Worked it~
